<?php

/*
|--------------------------------------------------------------------------
| Laravel 11+ bootstrap/app.php - middleware registration
|--------------------------------------------------------------------------
| If your fresh Laravel installation uses this file (Laravel 11/12 - no
| app/Http/Kernel.php exists), MERGE the withMiddleware() section below
| into your existing bootstrap/app.php. Keep the rest of the file
| (return Application::configure(...)) as generated by Laravel.
|
| If your installation still has app/Http/Kernel.php (Laravel 10), use
| app/Http/Kernel.php.example in this folder instead.
*/

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        api: __DIR__.'/../routes/api.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        $middleware->alias([
            'role' => \App\Http\Middleware\EnsureRole::class,
            'active' => \App\Http\Middleware\EnsureActiveUser::class,
        ]);
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();
